import mortalCombat from '@/assets/mortalCombat/mortalCombat.jpg'
import assassinsCreedOdyssey from '@/assets/assassinsCreed/assassinsCreedOdyssey.jpg'
import assassinsCreedSyndicate from '@/assets/assassinsCreed/assassinsCreedSyndicate.jpg'
import apexLegend from '@/assets/apexLegend/apexLegend.jpg'
import devilMayCry from '@/assets/devilMayCry/devilMayCry.jpg'
import fifa from '@/assets/fifa/fifa.jpg'
import pubg from '@/assets/pubg/pubg.jpg'
import theLastOfUs from '@/assets/theLastOfUs/theLastOfUs.jpg'
import watchDogs from '@/assets/watchDogs/watchDogs.jpg'
import godOfWar from '@/assets/godOfWar/godOfWar.jpg'
import gtaV from '@/assets/gtaV/gtaV.jpg'
import battleFieldV from '@/assets/battleFieldV/battleFieldV.jpg'
import cyberPunk from '@/assets/cyberPunk/cyberPunk.jpg'
import residentEvil6 from '@/assets/residentEvil6/residentEvil6.jpg'
import eldenRing from '@/assets/eldenRing/eldenRing.jpg'
import minecraft from '@/assets/minecraft/minecraft.jpg'
import genshinImpact from '@/assets/genshinImpact/genshinImpact.webp'
import valorant from '@/assets/valorant/valorant.jpg'
import leaugeOfLegends from '@/assets/leaugeOfLegends/leaugeOfLegends.jpg'
import ghostOfTsushima from '@/assets/ghostOfTsushima/ghostOfTsushima.jpg'
import assassinsCreedMirage from '@/assets/assassinsCreed/assassinsCreedMirage.jpg'

export const games = [
    {
        name: 'اساسینز کرید سیندیکیت',
        price: 100000,
        type: 'بازی',
        image: assassinsCreedSyndicate,
        category: 'game',
        style: 'historical',
        platforms: ['ps', 'xbox', 'pc'],
        company: 'ubisoft',
        slug: 'assassinsCreedSyndicate',
    },
    {
        name: "لیگ آف لجندز",
        price: 180000,
        type: "گیفت کارد",
        image: leaugeOfLegends,
        category: "giftCard",
        style: "hackAndSlash",
        platforms: ["ps", "pc", "xbox"],
        company: "epicGames",
        slug: 'leaugeOfLegends',
    },
    {
        name: 'جی تی ای 5',
        price: 100000,
        type: 'دیسک',
        image: gtaV,
        category: 'disk',
        style: 'openWorld',
        platforms: ['ps', 'xbox', 'pc'],
        company: 'rockStar',
        slug: 'gtaV',
    },
    {
        name: "ماینکرفت",
        price: 400000,
        type: "بازی",
        image: minecraft,
        category: "game",
        style: "openWorld",
        platforms: ["pc", "ps", 'xbox'],
        company: "microsoft",
        slug: 'minecraft',
    },
    {
        name: 'خدای جنگ',
        price: 400000,
        type: 'بازی',
        image: godOfWar,
        category: 'game',
        style: 'hackAndSlash',
        platforms: ['ps'],
        company: 'sony',
        slug: 'godOfWar',
    },
    {
        name: "گوست آف تسوشیما",
        price: 400000,
        type: "بازی",
        image: ghostOfTsushima,
        category: "game",
        style: "shooter",
        platforms: ["ps"],
        company: "epicGames",
        slug: 'ghostOfTsushima',
    },
    {
        name: 'ایپکس لجند',
        price: 200000,
        type: 'گیفت کارد',
        image: apexLegend,
        category: 'giftCard',
        style: 'battleRoyal',
        platforms: ['ps', 'pc', 'nintendo', 'xbox'],
        company: 'electronicArts',
        slug: 'apexLegend',
    },
    {
        name: 'لست آف اس 2',
        price: 200000,
        type: 'بازی',
        image: theLastOfUs,
        category: 'game',
        style: 'shooter',
        platforms: ['ps'],
        company: 'sony',
        slug: 'theLastOfUs',
    },
    {
        name: "گنشین ایمپکت",
        price: 80000,
        type: "گیفت کارت",
        image: genshinImpact,
        category: "giftCard",
        style: "openWorld",
        platforms: ["ps"],
        company: "epicGames",
        slug: 'genshinImpact',
    },
    {
        name: 'پابجی',
        price: 150000,
        type: 'گیفت کارد',
        image: pubg,
        category: 'giftCard',
        style: 'battleRoyal',
        platforms: ['xbox', 'ps', 'pc'],
        company: 'sony',
        slug: 'pubg',
    },
    {
        name: 'مورتال کامبت 11',
        price: 0,
        type: 'دیسک',
        image: mortalCombat,
        category: 'disk',
        style: 'fighting',
        platforms: ['nintendo', 'pc', 'ps', 'xbox'],
        company: 'electronicArts',
        slug: 'mortalCombat',
    },
    {
        name: 'بتلفیلد 5',
        price: 150000,
        type: 'بازی',
        image: battleFieldV,
        category: 'game',
        style: 'shooter',
        platforms: ['xbox', 'ps', 'pc'],
        company: 'electronicArts',
        slug: 'battleFieldV',
    },
    {
        name: 'فیفا 2020',
        price: 0,
        type: 'دیسک',
        image: fifa,
        category: 'disk',
        style: 'sports',
        platforms: ['xbox', 'ps', 'pc', 'nintendo'],
        company: 'electronicArts',
        slug: 'fifa',
    },
    {
        name: "اساسینز کرید میراج",
        price: 450000,
        type: "بازی",
        image: assassinsCreedMirage,
        category: "game",
        style: "historical",
        platforms: ["pc"],
        company: "ubisoft",
        slug: 'assassinsCreedMirage',
    },
    {
        name: 'دویل می کرای 5',
        price: 0,
        type: 'دیسک',
        image: devilMayCry,
        category: 'disk',
        style: 'hackAndSlash',
        platforms: ['xbox', 'ps', 'pc'],
        company: 'capcom',
        slug: 'devilMayCry',
    },

    {
        name: 'اساسینز کرید آدیسی',
        price: 50000,
        type: 'بازی',
        image: assassinsCreedOdyssey,
        category: 'game',
        style: 'historical',
        platforms: ['xbox', 'ps', 'pc', 'nintendo'],
        company: 'ubisoft',
        slug: 'assassinsCreedOdyssey',
    },
    {
        name: 'واچ داگز 2',
        price: 150000,
        type: 'بازی',
        image: watchDogs,
        category: 'game',
        style: 'openWorld',
        platforms: ['xbox', 'ps', 'pc'],
        company: 'ubisoft',
        slug: 'watchDogs',
    },

    {
        name: "سایبرپانک ",
        price: 100000,
        type: "دیسک",
        image: cyberPunk,
        category: "disk",
        style: "openWorld",
        platforms: ["pc", "ps", "xbox"],
        company: "atari",   
        slug: 'cyberPunk',
    },
    {
        name: "رزیدنت اویل 6",
        price: 130000,
        type: "دیسک",
        image: residentEvil6,
        category: "disk",
        style: "shooter",
        platforms: ["pc", "ps", "xbox"],
        company: "capcom",
        slug: 'residentEvil6',
    },

    {
        name: "الدن رینگ",
        price: 500000,
        type: "بازی",
        image: eldenRing,
        category: "game",
        style: "openWorld",
        platforms: ["pc", "ps", "xbox"],
        company: "sony",
        slug: 'eldenRing',
    },
    {
        name: "والورانت",
        price: 120000,
        type: "گیفت کارت",
        image: valorant,
        category: "giftCard",
        style: "battleRoyal",
        platforms: ["ps", "pc"],
        company: "epicGames",
        slug: 'valorant',
    },
]
