import { MainTheme } from '@/theme/theme'
import './globals.css'
import { Vazirmatn } from 'next/font/google'
import {MainContext} from '@/context/mainContext'
const vazir = Vazirmatn({
  subsets: ['arabic', 'latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir='rtl' className={vazir.className}>
      <body>
        <MainTheme>
          <MainContext>
            {children}
          </MainContext>
        </MainTheme>
      </body>
    </html >
  )
}
