import { MainTheme } from '@/theme/theme'
import './globals.css'
import { Vazirmatn } from 'next/font/google'
import { MainContext } from '@/context/mainContext'
import DesktopHeader from '@/components/DesktopHeader'
import MobileHeader from '@/components/MobileHeader'
import { Box } from '@mui/material'
import Footer from '@/components/Footer'
import { StyledEngineProvider } from '@mui/material/styles'
import localFont from 'next/font/local'
// const vazir = localFont({
//   src: './Vazir.woff2',
//   display: 'swap'
// })
const vazir = Vazirmatn({
  subsets: ['arabic', 'latin'],
  display: 'swap',
})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir='rtl' className={vazir.className}>
      <body>
        <StyledEngineProvider injectFirst>
          <MainTheme>
            <MainContext>
              <DesktopHeader />
              <MobileHeader />
              <Box sx={{ backgroundColor: '#101820', zIndex: 0, position: 'relative' }}>
                {children}
                <Footer />
              </Box>
            </MainContext>
          </MainTheme>
        </StyledEngineProvider>
      </body>
    </html >
  )
}
